Merge FreeBSD main in with HyperTrace and DDTrace changes.

diff --git a/usr.sbin/bsdinstall/scripts/script b/usr.sbin/bsdinstall/scripts/script
--- a/usr.sbin/bsdinstall/scripts/script
+++ b/usr.sbin/bsdinstall/scripts/script
@@ -101,7 +101,7 @@ if [ "$BSDINSTALL_LOG" != "${debugFile#+}" ]; then
 	export debugFile="$BSDINSTALL_LOG"
 	f_quietly f_debug_init
 	# NB: Being scripted, let debug go to terminal for invalid debugFile
-	f_dprintf "Began Instalation at %s" "$( date )"
+	f_dprintf "Began Installation at %s" "$( date )"
 fi
 
 # Make partitions
@@ -111,19 +111,41 @@ if [ "$ZFSBOOT_DISKS" ]; then
 	bsdinstall zfsboot
 else
 	bsdinstall scriptedpart "$PARTITIONS"
-	bsdinstall mount
 fi
+bsdinstall mount
+
+# Fetch missing distribution files, if any
+exec 3>&1
+export BSDINSTALL_DISTDIR=$(`dirname $0`/fetchmissingdists 2>&1 1>&3)
+FETCH_RESULT=$?
+exec 3>&-
+
+[ $FETCH_RESULT -ne 0 ] && error "Could not fetch remote distributions"
 
 # Unpack distributions
 bsdinstall checksum
-for set in $DISTRIBUTIONS; do
-	f_dprintf "Extracting $BSDINSTALL_DISTDIR/$set"
-	# XXX: this will fail if any mountpoints are FAT, due to inability to
-	# set ctime/mtime on the root of FAT partitions. tar has no option to
-	# ignore this. We probably need to switch back to distextract here
-	# to properly support EFI.
-	tar -xf "$BSDINSTALL_DISTDIR/$set" -C $BSDINSTALL_CHROOT
-done
+if [ -t 0 ]; then
+	# If install is a tty, use distextract as normal
+	bsdinstall distextract
+else
+	# Otherwise, we need to use tar (see https://reviews.freebsd.org/D10736)
+	for set in $DISTRIBUTIONS; do
+		f_dprintf "Extracting $BSDINSTALL_DISTDIR/$set"
+		# XXX: The below fails if any mountpoints are FAT, due to
+		# inability to set ctime/mtime on the root of FAT partitions,
+		# which is needed to support e.g. EFI system partitions. tar has
+		# no option to ignore this (distextract ignores them internally
+		# through a hack), and returns 1 on any warning or error,
+		# effectively turning all warnings into fatal errors.
+		# 
+		# Work around this in an extremely lame way for the specific
+		# case of EFI system partitions only. This *ONLY WORKS* if
+		# /boot/efi is empty and does not handle analagous problems on
+		# other systems (ARM, PPC64).
+		tar -xf "$BSDINSTALL_DISTDIR/$set" -C $BSDINSTALL_CHROOT --exclude boot/efi
+		mkdir -p $BSDINSTALL_CHROOT/boot/efi
+	done
+fi
 
 # Configure bootloader if needed
 bsdinstall bootconfig
@@ -149,9 +171,8 @@ fi
 bsdinstall entropy
 if [ "$ZFSBOOT_DISKS" ]; then
 	zpool export $ZFSBOOT_POOL_NAME
-else
-	bsdinstall umount
 fi
+bsdinstall umount
 
 f_dprintf "Installation Completed at %s" "$( date )"
 
